sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t amdad/docker-react .
scripts:
  - docker run -e CI=true amdad/docker-react npm run test -- --coverage