sudo: required
language: generic
services:
  - docker

before_install:
  - gem install bundler
  - docker build -t amdad/docker-react -f Dockerfile.dev .

scripts:
  - docker run amdad/docker-react npm run test -- --coverage