sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t amdad/docker-react -f ./Dockerfile.dev .
script:
  - docker run -e CI=true amdad/docker-react npm run test -- --coverage
